apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
          resources:
            requests:
              memory: "100Mi"
              cpu: 500m
            limits:
              cpu: "1"
              memory: "200Mi"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"






             