apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: yoda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
      - name: backend-container
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"  
        