# Generated by Django 4.2.6 on 2023-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name_target', models.CharField(max_length=100)),
                ('prioritization_attack', models.IntegerField()),
                ('Latitude_coordinates', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Longitudinal_coordinates', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Enemy_organization', models.CharField(max_length=100)),
                ('Designation_targets', models.CharField(max_length=100)),
                ('target_was_attacked', models.BooleanField()),
                ('target_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
