# Generated by Django 4.2.6 on 2023-10-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='prioritization_attack',
            new_name='attack_priority',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='Latitude_coordinates',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='Longitudinal_coordinates',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='Designation_targets',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='name_target',
            new_name='target_goal',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_ID',
            new_name='target_id',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_was_attacked',
            new_name='was_target_destroyed',
        ),
    ]
