# Generated by Django 4.2.6 on 2023-10-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_prioritization_attack_target_attack_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='Enemy_organization',
            new_name='enemy_organization',
        ),
    ]
