# Generated by Django 4.2.6 on 2023-10-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='groups',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
