# Generated by Django 4.2.6 on 2023-10-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('hometown', models.CharField(max_length=50)),
            ],
        ),
    ]
