# Generated by Django 4.2.6 on 2023-10-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('work_space', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child', models.ManyToManyField(related_name='child', to='people.person')),
            ],
            bases=('people.person',),
        ),
    ]
