# Generated by Django 4.2.6 on 2023-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
