# Generated by Django 4.2.6 on 2023-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_parent_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(null=True, related_name='child', to='people.person'),
        ),
    ]
