# Generated by Django 4.2.6 on 2023-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_parent_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(default=[], related_name='parents', to='people.person'),
        ),
    ]
