# Generated by Django 4.2.4 on 2023-10-19 13:12

from django.db import migrations, models
from django.core.validators import MaxValueValidator, MinValueValidator


def round_convert_to_int(apps, schema_editor):
    Model = apps.get_model('people', 'Parent')
    
    for instance in Model.objects.all():
        instance.salary = int(round(instance.salary))
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_parent_child'),
    ]

    operations = [
        migrations.RunPython(round_convert_to_int),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999)]),
        ),
    ]
