# Generated by Django 4.2.6 on 2023-10-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('waiting_response', 'Waiting for Response'), ('waiting_handling', 'Waiting for Handling')], max_length=20)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('shared_users', models.ManyToManyField(related_name='shared_events', to='user.user')),
            ],
        ),
    ]
