# Generated by Django 4.2.6 on 2023-10-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to='user.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('waiting_response', 'Waiting for Response'), ('waiting_handling', 'Waiting for Handling')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='Event_file',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.event')),
                ('opening_file_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            bases=('form.event',),
        ),
    ]
