# Generated by Django 4.2.6 on 2023-10-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('chat', '0001_initial'),
        ('form', '0002_alter_event_shared_users_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_file',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Event_chat',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.event')),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            bases=('form.event',),
        ),
    ]
