# Generated by Django 4.2.6 on 2023-10-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_event_file_file_event_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_chat',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='event_chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='event_chat',
            name='text',
        ),
    ]
